spring:
  application:
    name: reactive-java

data:
  initialGenearteDelayNs: "10000"
  initialHandleDelayNs: "100000"
  queueScaleSize: "10000"
  scaleDelayMillis: "3000"
  maxThreads: "20"
  accountQty: "100"
  tickers:
    - AFLT
    - ALRS
    - LKOH
    - MOEX
    - TATN
    - YDEX
    - RSTI
    - FLOT
    - VKCO
    - TCSI
    - OZON
    - POLY
    - ROSN