spring:
  application:
    name: reactive-java

data:
  dealQty:
    - "5000"
  serviceType: OBSERVABLE
  delayEnabled: true
  accountQty: "100"
  tickers:
    - AFLT
    - ALRS
    - LKOH
    - MOEX
    - TATN
    - YDEX
    - RSTI
    - FLOT
    - VKCO
    - TCSI
    - OZON
    - POLY
    - ROSN